# Generated by Django 2.0.6 on 2018-09-16 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopingcart', '0002_auto_20180426_0249'),
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=800)),
                ('Description', models.CharField(max_length=800)),
                ('ItemImage', models.CharField(max_length=800)),
            ],
        ),
    ]
