# Generated by Django 2.1 on 2018-09-07 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=800)),
                ('Description', models.CharField(max_length=800)),
                ('ItemImage', models.CharField(max_length=800)),
            ],
        ),
    ]
