# Generated by Django 2.1 on 2018-08-28 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_books'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoviesList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MovieName', models.CharField(max_length=200)),
                ('MovieGener', models.CharField(max_length=400)),
                ('MovieLanguage', models.CharField(max_length=400)),
                ('Moviecomment', models.CharField(max_length=400)),
                ('MovieUserName', models.CharField(max_length=400)),
                ('MovieUserEmail', models.CharField(max_length=400)),
            ],
        ),
    ]
