# Generated by Django 2.1 on 2018-08-28 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_movieslist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movieslist',
            name='MovieUserEmail',
        ),
        migrations.RemoveField(
            model_name='movieslist',
            name='MovieUserName',
        ),
        migrations.RemoveField(
            model_name='movieslist',
            name='Moviecomment',
        ),
    ]
